name: copy Readme content to another repo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: 
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Checkout repo data
        uses: actions/checkout@v3
      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: sashosotirov/kubernetes_wildfly
          path: kubernetes_wildfly

      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          cat ${{ github.workspace }}/kubernetes_wildfly/README.md >> README.md
          echo `cat README.md`
          git add .
          git commit -m "update README file"
          git push:
      - run: echo "This job's status is ${{ job.status }}."