name: copy Readme content to another repo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: 
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          pwd
          ls ${{ github.workspace }}
          echo "add some text again" >> ls `ls | grep README.md`
          cat README.md
      - run: echo "This job's status is ${{ job.status }}."