name: update Readme.md content
run-name: '${{ github.actor }} is testing out HW_Task_4'
'on':
  push: null
jobs:
  HW_Task_4:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: sashosotirov/kubernetes_wildfly
      EMAIL: sotirov.sasho@gmail.com
    steps:
      - name: Checkout repo data
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: '${{ REMOTE_REPO }}'
          path: remoterepo
          token: '${{ secrets.GH_PAT }}'
      - run: echo " The repositories have been cloned to the runner."
      - name: Update README.md file
        run: |
          cat ${{ github.workspace }}/remoterepo/README.md >> main/README.md
                              
      - name: Push changes
        run: |
          cd ${{ github.workspace }}/main
          git config user.name ${{ github.actor }}
          git config user.email ${{ env.EMAIL }}
          git add .
          git commit -m "Automatic Readme file update"
          git push
