
name: update Readme.md content
run-name: ${{ github.actor }} is testing out HW_Task_4 

on: 
  push:
  

jobs:
  HW_Task_4:
    runs-on: ubuntu-latest
    env: 
      REMOTEREPO_PATH: kubernetes_wildfly
      EMAIL: sotirov.sasho@gmail.com
           
        
    steps:
          
      - name:  Checkout repo data
        uses: actions/checkout@v3
        with:
          path: main
          
      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: sashosotirov/kubernetes_wildfly
          path: ${{ env.remoterepo_path }}
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains remote repo PAT
        
      - run: echo " The ${{ github.repository }} repositories have been cloned to the runner."

      - name: Update README.md file
        run: |
          cat ${{ github.workspace }}/${{ env.remoterepo_path }}/README.md >> main/README.md
                              
      - name: Push changes
        run: |
          cd ${{ github.workspace }}/main
          git config user.name ${{ github.actor }}
          git config user.email ${{ env.email }}
          git add .
          git commit -m "Automatic Readme file update"
          git push
        
     
         