name: copy Readme content to another repo
run-name: ${{ github.actor }} is testing out GitHub Actions 

on: 
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
          
      - name:  Checkout repo data
        uses: actions/checkout@v3
        with:
          path: main
          

      - name: Checkout remote repo
        uses: actions/checkout@v3
        with:
          repository: sashosotirov/kubernetes_wildfly
          path: kubernetes_wildfly
        

      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          cat ${{ github.workspace }}/kubernetes_wildfly/README.md >> main/README.md
          echo `cat main/README.md`          
      - run: echo "This job's status is ${{ job.status }}."
     
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Automated updating of the README file
          commit_user_name: sashosotirov
          commit_user_email: sotirov.sasho@gmail.com
          

